// ================================================================
// TRIMURTI PRODUCT CATALOG — Edit this file to manage all products
// ================================================================
// HOW TO ADD A PRODUCT:
//   Copy a block below, paste it inside the PRODUCTS array,
//   fill in the fields, and save. The page builds itself.
//
// FIELDS:
//   id           unique slug (e.g. "maize")
//   name         product display name
//   category     "field-crops" | "vegetables" | "fodder"
//   type         "Hybrid" | "Variety"
//   code         internal product code (optional)
//   description  short description (1-2 lines)
//   features     array of key features (strings)
//   region       suitable region
//   season       suitable season
//   duration     crop duration
//   special      special traits (e.g. "Drought tolerant")
//   image        path to product image (optional)
//   pdf          path to brochure PDF (optional)
//   markets      market regions (optional)
//   active       true/false — set false to hide without deleting
//   order        display order within category (lower = first)
//   detailPage   true = has own detail page at crops/{id}.html
//   hybrids      array of { name, desc }
//
// NOTE: First entries (order 1-9 for field-crops, 1-10 for vegetables,
// 1-3 for fodder) are category summary cards with detail pages.
// All subsequent entries are individual SKU products.
// ================================================================

const PRODUCTS = [
  // ======================================================================
  // FIELD CROPS — Category Summary Cards (order 1-9)
  // ======================================================================
    {
      id: "maize",
      name: "Maize",
      category: "field-crops",
      type: "Hybrid",
      code: "TMR-MZ",
      active: true,
      order: 1,
      description: "High-yielding biotech and conventional maize hybrids for Kharif and Rabi seasons. Strong pest tolerance and excellent grain quality.",
      image: "images/products/maize.jpg",
      features: ["Biotech & conventional options", "Kharif & Rabi seasons", "Excellent stay-green trait", "High shelling percentage"],
      region: "Central & Southern India",
      season: "Kharif / Rabi",
      duration: "95-115 days",
      special: "Pest tolerant, drought tolerance",
      pdf: "brochures/maize.pdf",
      markets: "India, Nepal",
      detailPage: true,
      hybrids: [{name: "Nagma", desc: "Biotech Hybrid — Kharif"}, {name: "TMRH-1422", desc: "Biotech Hybrid — Rabi"}, {name: "TMRH-871", desc: "Conventional Hybrid"}]
      },
    {
      id: "rice",
      name: "Rice",
      category: "field-crops",
      type: "Hybrid",
      code: "TMR-RC",
      active: true,
      order: 2,
      description: "Premium rice hybrids across early, medium, and late duration groups. Long slender grains with excellent cooking quality.",
      image: "images/products/rice.jpg",
      features: ["Long slender grains", "Multiple maturity groups", "High tillering", "Good grain quality"],
      region: "All major rice-growing regions",
      season: "Kharif",
      duration: "100-145 days",
      special: "High yield potential",
      pdf: "brochures/rice.pdf",
      markets: "India, Nepal",
      detailPage: true,
      hybrids: [{name: "TMRH-221", desc: "Early Duration (100-110 days)"}, {name: "TMRH-335", desc: "Medium Duration (120-130 days)"}, {name: "TMRH-448", desc: "Late Duration (140-145 days)"}]
      },
    {
      id: "mustard",
      name: "Mustard",
      category: "field-crops",
      type: "Hybrid",
      code: "TMR-MS",
      active: true,
      order: 3,
      description: "High oil content mustard hybrids with excellent pod load and disease tolerance. Suitable for rainfed and irrigated conditions.",
      image: "images/products/mustard.jpg",
      features: ["Oil content 42-45%", "Pod shattering tolerance", "Good meal quality", "Aphid tolerance"],
      region: "Central & Northern India",
      season: "Rabi",
      duration: "85-120 days",
      special: "High oil content",
      pdf: "brochures/mustard.pdf",
      markets: "India",
      detailPage: true,
      hybrids: [{name: "TMRH-511", desc: "Early Hybrid (100-110 days)"}, {name: "TMRH-622", desc: "High Yield Hybrid (115-120 days)"}, {name: "TMRH-733", desc: "Short Duration Hybrid (85-95 days)"}]
      },
    {
      id: "bajra",
      name: "Bajra (Pearl Millet)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMR-BJ",
      active: true,
      order: 4,
      description: "Drought-tolerant pearl millet hybrids for rainfed and dryland conditions. Excellent grain filling and dual-purpose options.",
      image: "images/products/bajra.jpg",
      features: ["Drought tolerance", "Dual-purpose options", "Good grain quality", "Downy mildew tolerance"],
      region: "Arid & Semi-arid zones",
      season: "Kharif",
      duration: "75-90 days",
      special: "Drought tolerant",
      pdf: "brochures/bajra.pdf",
      markets: "India",
      detailPage: true,
      hybrids: [{name: "TMRB-101", desc: "Drought Tolerant Hybrid"}, {name: "TMRB-202", desc: "Dual Purpose Hybrid"}]
      },
    {
      id: "jowar",
      name: "Jowar (Sorghum)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMR-JW",
      active: true,
      order: 5,
      description: "Grain and dual-purpose sorghum hybrids with bold, lustrous grains. Excellent threshing recovery and fodder quality.",
      image: "images/products/jowar.jpg",
      features: ["Bold, white grains", "Dual-purpose options", "Shoot fly tolerance", "High biomass"],
      region: "Central & Western India",
      season: "Kharif / Rabi",
      duration: "100-115 days",
      special: "Dual purpose",
      pdf: "brochures/jowar.pdf",
      markets: "India",
      detailPage: true,
      hybrids: [{name: "TMRJ-301", desc: "Grain Hybrid (100-110 days)"}, {name: "TMRJ-402", desc: "Dual-Purpose Hybrid (105-115 days)"}]
      },
    {
      id: "sunflower",
      name: "Sunflower",
      category: "field-crops",
      type: "Hybrid",
      code: "TMR-SF",
      active: true,
      order: 6,
      description: "Oil and confectionery sunflower hybrids with excellent head size and seed filling. Suitable for Kharif and Rabi seasons.",
      image: "images/products/sunflower.jpg",
      features: ["High oil recovery", "Confectionery options", "Good head size", "Necrosis tolerance"],
      region: "Peninsular India",
      season: "Kharif / Rabi",
      duration: "85-100 days",
      special: "Oil & confectionery types",
      pdf: "brochures/sunflower.pdf",
      markets: "India",
      detailPage: true,
      hybrids: [{name: "TMRSF-501", desc: "Oil Hybrid (40-42% oil)"}, {name: "TMRSF-602", desc: "Confectionery Hybrid (Striped)"}]
      },
    {
      id: "cotton",
      name: "Cotton",
      category: "field-crops",
      type: "Hybrid",
      code: "TMR-CT",
      active: true,
      order: 7,
      description: "BG-II and conventional cotton hybrids with premium staple length. Effective bollworm protection and good boll retention.",
      image: "images/products/cotton.jpg",
      features: ["BG-II technology", "Premium staple (28-32 mm)", "Good boll retention", "Sucking pest tolerance"],
      region: "Central & Southern India",
      season: "Kharif",
      duration: "150-170 days",
      special: "BG-II technology",
      pdf: "brochures/cotton.pdf",
      markets: "India",
      detailPage: true,
      hybrids: [{name: "TMRC-701", desc: "BG-II Hybrid (Cry1Ac+Cry2Ab)"}, {name: "TMRC-802", desc: "Conventional Hybrid"}]
      },
    {
      id: "green-gram",
      name: "Green Gram",
      category: "field-crops",
      type: "Variety",
      code: "TMR-GG",
      active: true,
      order: 8,
      description: "Early and high-yielding green gram varieties with bold, shiny grains. Synchronous maturity for cleaner harvest.",
      image: "images/products/green-gram.jpg",
      features: ["Bold, shiny grains", "Synchronous maturity", "Good cooking quality", "YMD tolerance"],
      region: "All India",
      season: "Kharif / Summer",
      duration: "60-70 days",
      special: "Short duration",
      pdf: "brochures/green-gram.pdf",
      markets: "India",
      detailPage: true,
      hybrids: [{name: "TMRG-901", desc: "Early Variety (60-65 days)"}, {name: "TMRG-902", desc: "High Yield Variety (65-70 days)"}]
      },
    {
      id: "black-gram",
      name: "Black Gram",
      category: "field-crops",
      type: "Variety",
      code: "TMR-BG",
      active: true,
      order: 9,
      description: "Early and high-yielding black gram varieties with bold, lustrous grains. Excellent pod filling and market-preferred quality.",
      image: "images/products/black-gram.jpg",
      features: ["Bold, black, shiny grains", "Multiple picking", "Good pod filling", "BLB tolerance"],
      region: "All India",
      season: "Kharif / Rabi",
      duration: "65-75 days",
      special: "Bold grain type",
      pdf: "brochures/black-gram.pdf",
      markets: "India",
      detailPage: true,
      hybrids: [{name: "TMRB-951", desc: "Early Variety (65-70 days)"}, {name: "TMRB-952", desc: "High Yield Variety (70-75 days)"}]
      },
  // ----------------------------------------------------------------------
  // FIELD CROPS — Individual SKUs (order 10+)
  // ----------------------------------------------------------------------
    {
      id: "tmmh846",
      name: "TMMH 846",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH846",
      active: true,
      order: 10,
      description: "• Maize hybrid with high yield potential\n• Medium maturity (Kharif: 90 – 100 days) hybrid\n• Semi-...",
      image: "images/products/TMMH846.jpg",
      features: ["Maize hybrid with high yield potential", "Medium maturity (Kharif: 90 – 100 days) hybrid", "Semi-..."],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv1626",
      name: "TMRV 1626",
      category: "field-crops",
      type: "Variety",
      code: "TMRV1626",
      active: true,
      order: 11,
      description: "TMRV 1626 — variety from Trimurti Seeds.",
      image: "images/products/TMRV1626.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh806",
      name: "Trinath (TMMH 806)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH806",
      active: true,
      order: 12,
      description: "Trinath (TMMH 806) — hybrid from Trimurti Seeds.",
      image: "images/products/TMMH806.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh2858",
      name: "TMMH 2858",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH2858",
      active: true,
      order: 13,
      description: "• Premium Maize hybrid with very high yield potential\n• Full season maturity [Rabi: 120-130 days]...",
      image: "images/products/TMMH2858.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv1666",
      name: "BADRINATH (TMRV 1666)",
      category: "field-crops",
      type: "Variety",
      code: "TMRV1666",
      active: true,
      order: 14,
      description: "BADRINATH (TMRV 1666) — variety from Trimurti Seeds.",
      image: "images/products/TMRV1666.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv1734",
      name: "TMRV 1734",
      category: "field-crops",
      type: "Variety",
      code: "TMRV1734",
      active: true,
      order: 15,
      description: "TMRV 1734 — variety from Trimurti Seeds.",
      image: "images/products/TMRV1734.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv1686",
      name: "BAPPI (TMRV 1686)",
      category: "field-crops",
      type: "Variety",
      code: "TMRV1686",
      active: true,
      order: 16,
      description: "BAPPI (TMRV 1686) — variety from Trimurti Seeds.",
      image: "images/products/TMRV1686.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "pr-126",
      name: "PR 126",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 17,
      description: "PR 126 — hybrid from Trimurti Seeds.",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh5786",
      name: "TMRH 5786",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH5786",
      active: true,
      order: 18,
      description: "TMRH 5786 — hybrid from Trimurti Seeds.",
      image: "images/products/TMRH5786.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh102",
      name: "Kamakshi (TMRH 102)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH102",
      active: true,
      order: 19,
      description: "Kamakshi (TMRH 102) — hybrid from Trimurti Seeds.",
      image: "images/products/TMRH102.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh114",
      name: "MANI (TMRH 114)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH114",
      active: true,
      order: 20,
      description: "MANI (TMRH 114) — hybrid from Trimurti Seeds.",
      image: "images/products/TMRH114.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh2106",
      name: "TMRH 2106",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH2106",
      active: true,
      order: 21,
      description: "• Full seasong maturing [Kharif: 130-135 days (North & South India) 135-140 days (East & Central ...",
      image: "images/products/TMRH2106.jpg",
      features: [],
      pdf: "brochures/TMRH2106.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh106",
      name: "GULABOO (TMRH 106)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH106",
      active: true,
      order: 22,
      description: "• Mid-early maturing (Kharif: 116-122 days) basmati rice hybrid\nwith higher yield potential\n• Sem...",
      image: "images/products/TMRH106.jpg",
      features: [],
      pdf: "brochures/TMRH106.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh108",
      name: "PAVITRA (TMRH 108)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH108",
      active: true,
      order: 23,
      description: "• Early maturing (Kharif: 115-120 days) Basmati Rice hybrid\nwith high yield potential\n• Semi-erec...",
      image: "images/products/TMRH108.jpg",
      features: [],
      pdf: "brochures/TMRH108.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh2171",
      name: "Chetak (TMRH 2171)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH2171",
      active: true,
      order: 24,
      description: "CHETAK (TMRH 2171)\n• Early maturing (Kharif: 112-117 days) Basmati Rice hybrid\nyield potential\n• ...",
      image: "images/products/TMRH2171.jpg",
      features: [],
      pdf: "brochures/TMRH2171.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh2112",
      name: "Chetak Gold (TMRH 2112)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH2112",
      active: true,
      order: 25,
      description: "CHETAK GOLD (TMRH 2112)\n• Mid-early maturing (Kharif: 118-125 days) hybrid basmati rice with high...",
      image: "images/products/TMRH2112.jpg",
      features: [],
      pdf: "brochures/TMRH2112.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh5544",
      name: "TMRH 5544",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH5544",
      active: true,
      order: 26,
      description: "• Medium maturing (Kharif: 115-120 days & Rabi: 125-135 days) hybrid\nwith very high yield potenti...",
      image: "images/products/TMRH5544.jpg",
      features: [],
      pdf: "brochures/TMRH5544.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh826",
      name: "TMMH 826",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH826",
      active: true,
      order: 27,
      description: "• Premium Maize hybrid with very high yield potential\n• Full season maturity [Kharif: 105-110 day...",
      image: "images/products/TMMH826.jpg",
      features: [],
      pdf: "brochures/TMMH826.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh2156",
      name: "TMRH 2156",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH2156",
      active: true,
      order: 28,
      description: "TMRH 2156 — hybrid from Trimurti Seeds.",
      image: "images/products/TMRH2156.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh824",
      name: "TMMH 824",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH824",
      active: true,
      order: 29,
      description: "TMMH 824 — hybrid from Trimurti Seeds.",
      image: "images/products/TMMH824.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh2161",
      name: "TMRH 2161",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH2161",
      active: true,
      order: 30,
      description: "• Medium maturing [Kharif: 115-125 days and Rabi: 125-135 days] Rice hybrid with high yield poten...",
      image: "images/products/TMRH2161.jpg",
      features: [],
      pdf: "brochures/TMRH2161.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh2845",
      name: "Devaraj (TMMH 2845)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH2845",
      active: true,
      order: 31,
      description: "Devaraj (TMMH 2845) — hybrid from Trimurti Seeds.",
      image: "images/products/TMMH2845.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh129",
      name: "TMRH 129",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH129",
      active: true,
      order: 32,
      description: "• Early maturing [Kharif: 108-112 days (North India) & 115-120 days\n(East & Central India)] Rice ...",
      image: "images/products/TMRH129.jpg",
      features: [],
      pdf: "brochures/TMRH129.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh2882",
      name: "SUVEER (TMMH 2882)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH2882",
      active: true,
      order: 33,
      description: "SUVEER (TMMH 2882) — hybrid from Trimurti Seeds.",
      image: "images/products/TMMH2882.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh124",
      name: "TMRH 124",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH124",
      active: true,
      order: 34,
      description: "• Medium maturing (Kharif: 125-130 days) hybrid with high yield potential\n• Semi-erect plant habi...",
      image: "images/products/TMRH124.jpg",
      features: [],
      pdf: "brochures/TMRH124.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh8842",
      name: "TMMH 8842",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH8842",
      active: true,
      order: 35,
      description: "• Premium Maize hybrid with high yield potential\n• Medium maturity (Kharif: 90-100 days) hybrid\n•...",
      image: "images/products/TMMH8842.jpg",
      features: [],
      pdf: "brochures/TMMH8842.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh5556",
      name: "TMRH 5556",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH5556",
      active: true,
      order: 36,
      description: "• Medium maturing [Kharif: 125-130 days (North & South India) &\n135-140 days (East & Central Indi...",
      image: "images/products/TMRH5556.jpg",
      features: [],
      pdf: "brochures/TMRH5556.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh2852",
      name: "TMMH 2852",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH2852",
      active: true,
      order: 37,
      description: "TMMH 2852 — hybrid from Trimurti Seeds.",
      image: "images/products/TMMH2852.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh5750",
      name: "TMRH 5750",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH5750",
      active: true,
      order: 38,
      description: "• Mid-early maturing [Kharif: 115-120 days (North & South India) & 120-125 days (East & Central I...",
      image: "images/products/TMRH5750.jpg",
      features: [],
      pdf: "brochures/TMRH5750.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh111",
      name: "Sarna (TMRH 111)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH111",
      active: true,
      order: 39,
      description: "SARNA (TMRH 111)\n• Medium maturing [Kharif: 115-120 days (North & South India) &\n120-125 days (Ea...",
      image: "images/products/TMRH111.jpg",
      features: [],
      pdf: "brochures/TMRH111.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh812",
      name: "TMMH 812",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH812",
      active: true,
      order: 40,
      description: "• Maize hybrid with high yield potential\n• Early maturity (Kharif :85-90 days and Rabi: 115-125 d...",
      image: "images/products/TMMH812.jpg",
      features: [],
      pdf: "brochures/TMMH812.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh2151",
      name: "TMRH 2151",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH2151",
      active: true,
      order: 41,
      description: "• Full season maturing [Kharif: 135 -145 days] rice hybrid\nwith high yield potential\n• Semi-erect...",
      image: "images/products/TMRH2151.jpg",
      features: [],
      pdf: "brochures/TMRH2151.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh826",
      name: "TMMH 826.COM",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH826",
      active: true,
      order: 42,
      description: "TMMH 826.COM — hybrid from Trimurti Seeds.",
      image: "images/products/TMMH826.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh5535",
      name: "TMRH 5535",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH5535",
      active: true,
      order: 43,
      description: "TMRH 5535 — hybrid from Trimurti Seeds.",
      image: "images/products/TMRH5535.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "devaki-jrh-and-8211--5",
      name: "Devaki (JRH &#8211; 5)",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 44,
      description: "Devaki (JRH &#8211; 5) — hybrid from Trimurti Seeds.",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh2135",
      name: "TMRH 2135",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH2135",
      active: true,
      order: 45,
      description: "TMRH 2135 — hybrid from Trimurti Seeds.",
      image: "images/products/TMRH2135.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh5513",
      name: "TMRH 5513 (Nagma)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH5513",
      active: true,
      order: 46,
      description: "TMRH 5513 (Nagma) — hybrid from Trimurti Seeds.",
      image: "images/products/TMRH5513.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh5559",
      name: "TMRH 5559",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH5559",
      active: true,
      order: 47,
      description: "TMRH 5559 — hybrid from Trimurti Seeds.",
      image: "images/products/TMRH5559.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh5788",
      name: "TMRH 5788",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH5788",
      active: true,
      order: 48,
      description: "TMRH 5788 — hybrid from Trimurti Seeds.",
      image: "images/products/TMRH5788.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh2184",
      name: "TMRH 2184",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH2184",
      active: true,
      order: 49,
      description: "TMRH2184\n• Early maturing [Kharif: 110-115 days]\nRice hybrid with high yield potential\n• Semi-ere...",
      image: "images/products/TMRH2184.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh101",
      name: "TMRH 101",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH101",
      active: true,
      order: 50,
      description: "• Early maturing [Kharif: 101-108 days & Rabi: 130-135 days] hybrid\nwith high yield potential\n• S...",
      image: "images/products/TMRH101.jpg",
      features: [],
      pdf: "brochures/TMRH101.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "trinath-turbo",
      name: "Trinath TURBO",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 51,
      description: "Trinath TURBO — hybrid from Trimurti Seeds.",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh8805",
      name: "TMMH 8805",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH8805",
      active: true,
      order: 52,
      description: "TMMH 8805 — hybrid from Trimurti Seeds.",
      image: "images/products/TMMH8805.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh8418",
      name: "TMMH 8418",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH8418",
      active: true,
      order: 53,
      description: "TMMH 8418 — hybrid from Trimurti Seeds.",
      image: "images/products/TMMH8418.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh807",
      name: "TMMH 807",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH807",
      active: true,
      order: 54,
      description: "• Maize hybrid with high yield potential\n• Medium maturity - Kharif: 90-95 days,\n• Suitable for h...",
      image: "images/products/TMMH807.jpg",
      features: [],
      pdf: "brochures/TMMH807.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh8135",
      name: "TMMH 8135",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH8135",
      active: true,
      order: 55,
      description: "TMMH 8135 — hybrid from Trimurti Seeds.",
      image: "images/products/TMMH8135.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh2861",
      name: "TMMH 2861",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH2861",
      active: true,
      order: 56,
      description: "TMMH 2861 — hybrid from Trimurti Seeds.",
      image: "images/products/TMMH2861.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh2840",
      name: "Darwin (TMMH 2840)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH2840",
      active: true,
      order: 57,
      description: "Darwin (TMMH 2840) — hybrid from Trimurti Seeds.",
      image: "images/products/TMMH2840.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh107",
      name: "DEVI (TMRH 107)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH107",
      active: true,
      order: 58,
      description: "•Medium maturing (Kharif: 125-130 days & Rabi: 130-135 days) hybrid with high yield potential\n• N...",
      image: "images/products/TMRH107.jpg",
      features: [],
      pdf: "brochures/TMRH107.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh8863",
      name: "RAJNATH (TMMH 8863)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH8863",
      active: true,
      order: 59,
      description: "RAJNATH (TMMH 8863) — hybrid from Trimurti Seeds.",
      image: "images/products/TMMH8863.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh8833",
      name: "TMMH 8833",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH8833",
      active: true,
      order: 60,
      description: "TMMH 8833 — hybrid from Trimurti Seeds.",
      image: "images/products/TMMH8833.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "shivi-fast",
      name: "Shivi Fast",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 61,
      description: "SHIVI FAST (TMRH 2110)\n• Early maturing [Kharif: 105-110 days (North & South India) & 110-115 (Ea...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "dhumdaar",
      name: "Dhumdaar",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 62,
      description: "Dhumdaar — hybrid from Trimurti Seeds.",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh174",
      name: "Supriya (TMRH 174)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH174",
      active: true,
      order: 63,
      description: "• Full season maturing (Kharif: 132-138 days & Rabi: 140-145 days)\nRice hybrid with very high yie...",
      image: "images/products/TMRH174.jpg",
      features: [],
      pdf: "brochures/TMRH174.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv3615",
      name: "DUMDAAR (TMRV 3615)",
      category: "field-crops",
      type: "Variety",
      code: "TMRV3615",
      active: true,
      order: 64,
      description: "DUMDAAR (TMRV 3615) — variety from Trimurti Seeds.",
      image: "images/products/TMRV3615.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh2838",
      name: "Fodder (TMMH2838)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH2838",
      active: true,
      order: 65,
      description: "Fodder (TMMH2838) — hybrid from Trimurti Seeds.",
      image: "images/products/TMMH2838.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "ghungroo-tmmd-99",
      name: "Ghungroo (TMMD 99)",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 66,
      description: "GHUNGROO (TMMD 99)\n• Yellow Mustard variety\n• Medium maturity: 100-110 days\n• Plant height: 115-1...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "jewel-tmsf-1701",
      name: "Jewel (TMSF 1701)",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 67,
      description: "JEWEL (TV1SH 1701)\n• Sunflower hybrid suitable for both medium and light soils\n• High yield poten...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "julie-tmmd-97",
      name: "Julie (TMMD 97)",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 68,
      description: "JULIE (TMMD 97)\n• Yellow Mustard variety\n• Early maturity: 98-104 days\n• Plant height: 110-120 cm...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "kaalia-tmmd-92",
      name: "Kaalia (TMMD 92)",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 69,
      description: "KAALIA (TMMD 92)\n• Mustard variety with very high yield potential\n• Medium maturity: 125-135 days...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmd9242",
      name: "KAALIA GOLD (TMMD 9242)",
      category: "field-crops",
      type: "Variety",
      code: "TMMD9242",
      active: true,
      order: 70,
      description: "KAALIA GOLD (TMMD 9242) — variety from Trimurti Seeds.",
      image: "images/products/TMMD9242.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "kashinath-tmmd-91",
      name: "Kashinath (TMMD 91)",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 71,
      description: "KASHINATH (TMMD 91)\n• Mustard variety with high yield potential\n• Medium maturity: 115-125 days\n•...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "lokpriya-tmw-3888",
      name: "Lokpriya (TMW 3888)",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 72,
      description: "LOKPRIYA (TMW 3888)\n• Wheat variety with very high yield potential\n• Semi-erect plant type\n• Days...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmbh633",
      name: "TMBH 633",
      category: "field-crops",
      type: "Hybrid",
      code: "TMBH633",
      active: true,
      order: 73,
      description: "• Medium maturing (Kharif: 80-85 days & Summer: 85-90 days) hybrid with very high yield potential...",
      image: "images/products/TMBH633.jpg",
      features: [],
      pdf: "brochures/TMBH633.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmbh680",
      name: "TMBH 680",
      category: "field-crops",
      type: "Hybrid",
      code: "TMBH680",
      active: true,
      order: 74,
      description: "• Early to medium maturing (Kharif: 78-82 days) hybrid with very high yield potential\n•Erect plan...",
      image: "images/products/TMBH680.jpg",
      features: [],
      pdf: "brochures/TMBH680.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmbh2652",
      name: "TMBH 2652",
      category: "field-crops",
      type: "Hybrid",
      code: "TMBH2652",
      active: true,
      order: 75,
      description: "Medium maturing (Kharif: 78-82 days & Summer: 84-90 days) hybrid with very high yield potential\n•...",
      image: "images/products/TMBH2652.jpg",
      features: [],
      pdf: "brochures/TMBH2652.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmbh2631",
      name: "TMBH 2631",
      category: "field-crops",
      type: "Hybrid",
      code: "TMBH2631",
      active: true,
      order: 76,
      description: "• Medium maturing (Kharif: 80-85 days & Summer: 85-90 days) Bajra hybrid with very high yield pot...",
      image: "images/products/TMBH2631.jpg",
      features: [],
      pdf: "brochures/TMBH2631.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmbh601",
      name: "TMBH 601",
      category: "field-crops",
      type: "Hybrid",
      code: "TMBH601",
      active: true,
      order: 77,
      description: "• Early to medium maturing (Kharif: 78-82 days) hybrid with very high yield potential\n•Erect plan...",
      image: "images/products/TMBH601.jpg",
      features: [],
      pdf: "brochures/TMBH601.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmbh602",
      name: "TMBH 602",
      category: "field-crops",
      type: "Hybrid",
      code: "TMBH602",
      active: true,
      order: 78,
      description: "• Early to medium maturing (Kharif: 78-82 days) hybrid with very high yield potential\n•Erect plan...",
      image: "images/products/TMBH602.jpg",
      features: [],
      pdf: "brochures/TMBH602.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmbh2627",
      name: "TMBH 2627",
      category: "field-crops",
      type: "Hybrid",
      code: "TMBH2627",
      active: true,
      order: 79,
      description: "TMBH 2627 — hybrid from Trimurti Seeds.",
      image: "images/products/TMBH2627.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmbh2612",
      name: "TMBH 2612",
      category: "field-crops",
      type: "Hybrid",
      code: "TMBH2612",
      active: true,
      order: 80,
      description: "• Medium maturing (Kharif: 80-85 days & Summer: 85-90 days) Bajra hybrid with very high yield pot...",
      image: "images/products/TMBH2612.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "mahipal-bajra",
      name: "Mahipal Bajra",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 81,
      description: "MAHIPAL (TI^BH 605)\n•Early maturing (Kharif: 75-80 days) hybrid with high yield potential\n• Erect...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh809",
      name: "SAINATH (TMMH 809)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH809",
      active: true,
      order: 82,
      description: "• Premium Maize hybrid with high yield potential\n• Medium maturity (Kharif: 90-100 days) hybrid\n•...",
      image: "images/products/TMMH809.jpg",
      features: [],
      pdf: "brochures/TMMH809.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "shaan-e-dawat-plus-1509",
      name: "Shaan-e-dawat plus (1509)",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 83,
      description: "Shaan-e-dawat plus (1509)\n•Early maturing (Kharif: 115-120 days) Basmati Rice variety with high y...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv1121",
      name: "SHAN-E-DAWAT (TMRV 1121)",
      category: "field-crops",
      type: "Variety",
      code: "TMRV1121",
      active: true,
      order: 84,
      description: "SHAN-E-DAWAT (TMRV 1121) — variety from Trimurti Seeds.",
      image: "images/products/TMRV1121.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv1509",
      name: "SHAN-E-DAWAT PLUS (TMRV 1509)",
      category: "field-crops",
      type: "Variety",
      code: "TMRV1509",
      active: true,
      order: 85,
      description: "SHAN-E-DAWAT PLUS (TMRV 1509) — variety from Trimurti Seeds.",
      image: "images/products/TMRV1509.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh1105",
      name: "SHER-E-BASMATI (TMRH 1105)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH1105",
      active: true,
      order: 86,
      description: "SHER-E-BASMATI (TMRH 1105) — hybrid from Trimurti Seeds.",
      image: "images/products/TMRH1105.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv1632",
      name: "Shurma (TMRV 1632)",
      category: "field-crops",
      type: "Variety",
      code: "TMRV1632",
      active: true,
      order: 87,
      description: "Shurma (TMRV 1632) — variety from Trimurti Seeds.",
      image: "images/products/TMRV1632.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "slym",
      name: "Slym",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 88,
      description: "SLYM (TMRV 3618)\n• Medium maturing [Kharif: 125 -130 days & Rabi: 130-135 day\nRice variety with h...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv1685",
      name: "SNIGDHA (TMRV 1685)",
      category: "field-crops",
      type: "Variety",
      code: "TMRV1685",
      active: true,
      order: 89,
      description: "SNIGDHA (TMRV 1685) — variety from Trimurti Seeds.",
      image: "images/products/TMRV1685.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh804",
      name: "Srinath (TMMH 804)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH804",
      active: true,
      order: 90,
      description: "Srinath (TMMH 804) — hybrid from Trimurti Seeds.",
      image: "images/products/TMMH804.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh844",
      name: "SUPER TRIVIKRAM (TMMH 844)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH844",
      active: true,
      order: 91,
      description: "SUPER TRIVIKRAM (TMMH 844) — hybrid from Trimurti Seeds.",
      image: "images/products/TMMH844.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tinku",
      name: "Tinku",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 92,
      description: "• Medium maturing (Kharif: 130-135 days and Rabi: 135-140 days) rice variety with high yield pote...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tm-09",
      name: "TM 09",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 93,
      description: "• Early maturing [Kharif: 115-120 days] Basmati Rice variety with high yield potential\n• Semi-ere...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "ustaad-tm-914",
      name: "Ustaad (TM 914)",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 94,
      description: "USTAAD (TM 914)\n• Mustard hybrid with very high yield potential\n• Maturity: 120-130 days\n• Plant ...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tm-917",
      name: "TM 917",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 95,
      description: "Mustard hybrid with very high yield potential\nGood performance under cold temperatures\n• Maturity...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tm-9988",
      name: "TM 9988",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 96,
      description: "TM 9988 — hybrid from Trimurti Seeds.",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tm-936",
      name: "TM 936",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 97,
      description: "TM 936 — hybrid from Trimurti Seeds.",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmbh622",
      name: "TMBH 622",
      category: "field-crops",
      type: "Hybrid",
      code: "TMBH622",
      active: true,
      order: 98,
      description: "• Medium maturing (Kharif: 85-90 days & Summer : 90-95 days) hybrid with very high yield potentia...",
      image: "images/products/TMBH622.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmd2901",
      name: "TMMD 2901",
      category: "field-crops",
      type: "Variety",
      code: "TMMD2901",
      active: true,
      order: 99,
      description: "• Medium maturing (118-122 days) Mustard variety with high yield potential\n• Erect plant with tal...",
      image: "images/products/TMMD2901.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmd2904",
      name: "TMMD 2904",
      category: "field-crops",
      type: "Variety",
      code: "TMMD2904",
      active: true,
      order: 100,
      description: "• Yellow Mustard variety with high yield potential\n• Medium maturity: 115-120 days\n• Plant height...",
      image: "images/products/TMMD2904.jpg",
      features: [],
      pdf: "brochures/TMMD2904.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmd2905",
      name: "TMMD 2905",
      category: "field-crops",
      type: "Variety",
      code: "TMMD2905",
      active: true,
      order: 101,
      description: "TMMD 2905 — variety from Trimurti Seeds.",
      image: "images/products/TMMD2905.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh2831",
      name: "TMMH 2831",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH2831",
      active: true,
      order: 102,
      description: "TMMH 2831 — hybrid from Trimurti Seeds.",
      image: "images/products/TMMH2831.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh2831",
      name: "TMMH 2831 Plus",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH2831",
      active: true,
      order: 103,
      description: "• Premium Maize hybrid with high yield potential\n• Medium maturity (Kharif: 95-100 days & Rabi: 1...",
      image: "images/products/TMMH2831.jpg",
      features: [],
      pdf: "brochures/TMMH2831.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh2834",
      name: "TMMH 2834",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH2834",
      active: true,
      order: 104,
      description: "• Maize hybrid with high yield potential\n• Medium maturity (Kharif: 90-100 days) hybrid\n• Droopin...",
      image: "images/products/TMMH2834.jpg",
      features: [],
      pdf: "brochures/TMMH2834.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "pusa-hqpm-and-8211--5-improved",
      name: "Pusa HQPM &#8211; 5 Improved",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 105,
      description: "• Premium Maize hybrid with very high yield potential\n• Medium maturity [Rabi: 120-125 days (AP &...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh2841",
      name: "TMMH 2841",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH2841",
      active: true,
      order: 106,
      description: "• Premium Maize hybrid with very high yield potential\n• Medium maturity [Rabi: 120-125 days (AP &...",
      image: "images/products/TMMH2841.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh2855",
      name: "TMMH 2855",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH2855",
      active: true,
      order: 107,
      description: "• Premium Maize hybrid with very high yield potential\n• Full season maturity [Rabi: 120-130 days ...",
      image: "images/products/TMMH2855.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh801",
      name: "TMMH 801",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH801",
      active: true,
      order: 108,
      description: "• Premium Maize hybrid with high yield potential\n• Full season maturity [Kharif: 105-110 days, Ra...",
      image: "images/products/TMMH801.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh836",
      name: "TMMH 836",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH836",
      active: true,
      order: 109,
      description: "• Premium Maize hybrid with very high yield potential\n• Medium maturity and duration is 95-100 da...",
      image: "images/products/TMMH836.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh846",
      name: "TMMH 846",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH846",
      active: true,
      order: 110,
      description: "• Maize hybrid with high yield potential\n• Medium maturity (Kharif: 90 - 100 days) hybrid\n• Semi-...",
      image: "images/products/TMMH846.jpg",
      features: [],
      pdf: "brochures/TMMH846.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh8862",
      name: "TMMH 8862",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH8862",
      active: true,
      order: 111,
      description: "TMMH 8862 — hybrid from Trimurti Seeds.",
      image: "images/products/TMMH8862.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrh124",
      name: "TMRH 124",
      category: "field-crops",
      type: "Hybrid",
      code: "TMRH124",
      active: true,
      order: 112,
      description: "• Medium maturing (Kharif: 120-125 days) hybrid with high yield potential\n• Semi-erect plant habi...",
      image: "images/products/TMRH124.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv1609",
      name: "TMRV 1609",
      category: "field-crops",
      type: "Variety",
      code: "TMRV1609",
      active: true,
      order: 113,
      description: "• Full Season maturing (Kharif: 150-155 days & Rabi: 142-148 days) Rice variety with high yield p...",
      image: "images/products/TMRV1609.jpg",
      features: [],
      pdf: "brochures/TMRV1609.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv1611",
      name: "TMRV 1611",
      category: "field-crops",
      type: "Variety",
      code: "TMRV1611",
      active: true,
      order: 114,
      description: "• Full Season maturing (Kharif: 140-145 days & Rabi: 145-155 days) Rice variety with high yield p...",
      image: "images/products/TMRV1611.jpg",
      features: [],
      pdf: "brochures/TMRV1611.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv1617",
      name: "TMRV 1617",
      category: "field-crops",
      type: "Variety",
      code: "TMRV1617",
      active: true,
      order: 115,
      description: "• Early maturing [Kharif: 100-105 days] rice variety with high\nyield potential\n• Semi-erect plant...",
      image: "images/products/TMRV1617.jpg",
      features: [],
      pdf: "brochures/TMRV1617.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv1626",
      name: "TMRV 1626 (Yamini)",
      category: "field-crops",
      type: "Variety",
      code: "TMRV1626",
      active: true,
      order: 116,
      description: "TMRV 1626 (Yamini) — variety from Trimurti Seeds.",
      image: "images/products/TMRV1626.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv1628",
      name: "TMRV 1628",
      category: "field-crops",
      type: "Variety",
      code: "TMRV1628",
      active: true,
      order: 117,
      description: "• Mid-early maturing (Kharif: 120-125 days) Rice variety with high yield potential\n• Semi-erect p...",
      image: "images/products/TMRV1628.jpg",
      features: [],
      pdf: "brochures/TMRV1628.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv1629",
      name: "TMRV 1629",
      category: "field-crops",
      type: "Variety",
      code: "TMRV1629",
      active: true,
      order: 118,
      description: "• Full Season maturing (Kharif: 150-155 days & Rabi: 155-160 days) Rice variety with high yield p...",
      image: "images/products/TMRV1629.jpg",
      features: [],
      pdf: "brochures/TMRV1629.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv1682",
      name: "TMRV 1682",
      category: "field-crops",
      type: "Variety",
      code: "TMRV1682",
      active: true,
      order: 119,
      description: "TMRV 1682 — variety from Trimurti Seeds.",
      image: "images/products/TMRV1682.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "pb-1692",
      name: "PB 1692",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 120,
      description: "• Early maturing (Kharif: 115-120 days) Basmati Rice variety\nwith high yield potential\n• Semi-ere...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "pb-1718",
      name: "PB 1718",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 121,
      description: "Medium maturing (Kharif: 13 5-140 days) Basmati Rice variety with high yield potential\n• Semi-ere...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv3641",
      name: "TMRV 3641",
      category: "field-crops",
      type: "Variety",
      code: "TMRV3641",
      active: true,
      order: 122,
      description: "Medium maturing [Kharif: 125-130 days and Rabi: 130-135 days]\nRice variety with high yield potent...",
      image: "images/products/TMRV3641.jpg",
      features: [],
      pdf: "brochures/TMRV3641.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv3644",
      name: "TMRV 3644",
      category: "field-crops",
      type: "Variety",
      code: "TMRV3644",
      active: true,
      order: 123,
      description: "Full Season maturing (Kharif: 140-145 days & Rabi: 145-155 days) variety with high yield potentia...",
      image: "images/products/TMRV3644.jpg",
      features: [],
      pdf: "brochures/TMRV3644.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv3649",
      name: "TMRV 3649",
      category: "field-crops",
      type: "Variety",
      code: "TMRV3649",
      active: true,
      order: 124,
      description: "• Mid - Early maturing [Kharif: 115-120 days & Rabi 120-125 days] Rice variety with high yield po...",
      image: "images/products/TMRV3649.jpg",
      features: [],
      pdf: "brochures/TMRV3649.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmw-3838",
      name: "TMW 3838",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 125,
      description: "• Very high yielding Wheat variety\n• Days to 50 % spike emergence: 95-105 days\n• Maturity duratio...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "trimurti-92-tmrv-92",
      name: "TRIMURTI 92 (TMRV 92)",
      category: "field-crops",
      type: "Hybrid",
      code: "",
      active: true,
      order: 126,
      description: "TRIMURTI 92 (TMRV 92) — hybrid from Trimurti Seeds.",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmmh802",
      name: "TRIVIKRAM  (TMMH 802)",
      category: "field-crops",
      type: "Hybrid",
      code: "TMMH802",
      active: true,
      order: 127,
      description: "TRIVIKRAM (TMMH 802)\n• Maize hybrid with very high yield potential\n• Full season maturity [Kharif...",
      image: "images/products/TMMH802.jpg",
      features: [],
      pdf: "brochures/TMMH802.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv1621",
      name: "USTAAD (TMRV 1621)",
      category: "field-crops",
      type: "Variety",
      code: "TMRV1621",
      active: true,
      order: 128,
      description: "USTAAD (TMRV 1621) — variety from Trimurti Seeds.",
      image: "images/products/TMRV1621.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmrv1610",
      name: "VISHWANATH (TMRV 1610)",
      category: "field-crops",
      type: "Variety",
      code: "TMRV1610",
      active: true,
      order: 129,
      description: "VISHWANATH (TMRV 1610) — variety from Trimurti Seeds.",
      image: "images/products/TMRV1610.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
  // ======================================================================
  // VEGETABLES — Category Summary Cards (order 1-10)
  // ======================================================================
    {
      id: "tomato",
      name: "Tomato",
      category: "vegetables",
      type: "Hybrid",
      code: "TMR-TO",
      active: true,
      order: 1,
      description: "High-yielding tomato hybrids for open-field and protected cultivation. Good fruit setting and disease tolerance.",
      image: "images/products/tomato.jpg",
      features: ["Open-field & protected", "Good fruit setting", "Disease tolerance", "Market-preferred shape"],
      region: "All India",
      season: "Kharif / Rabi / Summer",
      duration: "60-75 days",
      detailPage: false,
      hybrids: [{name: "Indeterminate", desc: "Open-field, high yield"}, {name: "Determinate", desc: "Protected cultivation"}]
      },
    {
      id: "brinjal",
      name: "Brinjal (Eggplant)",
      category: "vegetables",
      type: "Hybrid",
      code: "TMR-BR",
      active: true,
      order: 2,
      description: "Hybrid brinjal varieties with high yield potential and excellent fruit quality. Suitable for diverse growing conditions.",
      image: "images/products/brinjal.jpg",
      features: ["High yielding", "Glossy fruits", "Good shelf life", "Market preferred"],
      region: "All India",
      season: "Kharif / Rabi",
      duration: "70-85 days",
      detailPage: false,
      hybrids: [{name: "Long Purple", desc: "High-yielding, glossy"}, {name: "Round Green", desc: "Market preferred"}]
      },
    {
      id: "chilli",
      name: "Chilli",
      category: "vegetables",
      type: "Hybrid",
      code: "TMR-CH",
      active: true,
      order: 3,
      description: "Green and red chilli hybrids with high pungency and good drying recovery. Suitable for fresh market and processing.",
      image: "images/products/chilli.jpg",
      features: ["High pungency", "Good drying recovery", "Dark green colour", "High yield"],
      region: "All India",
      season: "Kharif / Rabi",
      duration: "75-90 days",
      detailPage: false,
      hybrids: [{name: "Green Chilli", desc: "High pungency, dark green"}, {name: "Red Chilli", desc: "Good drying recovery"}]
      },
    {
      id: "okra",
      name: "Okra (Lady's Finger)",
      category: "vegetables",
      type: "Hybrid",
      code: "TMR-OK",
      active: true,
      order: 4,
      description: "Tender, dark green okra hybrids with YVMV tolerance. Excellent field holding capacity and market preference.",
      image: "images/products/okra.jpg",
      features: ["YVMV tolerant", "Tender, dark green", "Good field holding", "High yield"],
      region: "All India",
      season: "Kharif / Summer",
      duration: "50-60 days",
      special: "YVMV tolerant",
      detailPage: false,
      hybrids: [{name: "Early Hybrid", desc: "Tender, dark green"}, {name: "High Yield", desc: "YVMV tolerant"}]
      },
    {
      id: "bottle-gourd",
      name: "Bottle Gourd",
      category: "vegetables",
      type: "Hybrid",
      code: "TMR-BG",
      active: true,
      order: 5,
      description: "Long and round bottle gourd hybrids with tender flesh and high yield potential.",
      image: "images/products/bottle-gourd.jpg",
      features: ["Tender flesh", "Long & round types", "High yield", "Good market preference"],
      region: "All India",
      season: "Kharif / Summer",
      duration: "55-65 days",
      detailPage: false,
      hybrids: [{name: "Long Hybrid", desc: "Tender, high yield"}, {name: "Round Hybrid", desc: "Premium variety"}]
      },
    {
      id: "ridge-gourd",
      name: "Ridge Gourd",
      category: "vegetables",
      type: "Hybrid",
      code: "TMR-RG",
      active: true,
      order: 6,
      description: "Early and high-yielding ridge gourd hybrids with long, dark green fruits and good shelf life.",
      image: "images/products/ridge-gourd.jpg",
      features: ["Long, dark green fruits", "Good shelf life", "High yield", "Early maturity"],
      region: "All India",
      season: "Kharif",
      duration: "50-60 days",
      detailPage: false,
      hybrids: [{name: "Early Hybrid", desc: "Long, dark green"}, {name: "High Yield", desc: "Good shelf life"}]
      },
    {
      id: "cabbage",
      name: "Cabbage",
      category: "vegetables",
      type: "Hybrid",
      code: "TMR-CB",
      active: true,
      order: 7,
      description: "Compact-headed cabbage hybrid with 60-day maturity. Good field holding and market-preferred shape.",
      image: "images/products/cabbage.jpg",
      features: ["Compact head", "60 days maturity", "Good field holding", "Market preferred"],
      region: "All India",
      season: "Rabi / Kharif",
      duration: "55-65 days",
      detailPage: false,
      hybrids: [{name: "Early Hybrid", desc: "Compact head, 60 days"}]
      },
    {
      id: "cauliflower",
      name: "Cauliflower",
      category: "vegetables",
      type: "Hybrid",
      code: "TMR-CF",
      active: true,
      order: 8,
      description: "Early and late cauliflower hybrids with snow-white curds. Good curd compactness and disease tolerance.",
      image: "images/products/cauliflower.jpg",
      features: ["Snow white curds", "Early & late types", "Good curd compactness", "Disease tolerance"],
      region: "All India",
      season: "Rabi / Kharif",
      duration: "55-75 days",
      detailPage: false,
      hybrids: [{name: "Early Hybrid", desc: "Curd formation 55 days"}, {name: "Late Hybrid", desc: "Snow white, 75 days"}]
      },
    {
      id: "cucumber",
      name: "Cucumber",
      category: "vegetables",
      type: "Hybrid",
      code: "TMR-CU",
      active: true,
      order: 9,
      description: "Open-field and protected cucumber hybrids with dark green fruits and high yield. Parthenocarpic options for protected cultivation.",
      image: "images/products/cucumber.jpg",
      features: ["Open-field & protected", "Parthenocarpic options", "Dark green fruits", "High yield"],
      region: "All India",
      season: "Kharif / Summer",
      duration: "50-60 days",
      detailPage: false,
      hybrids: [{name: "Open-field", desc: "High yield, dark green"}, {name: "Protected", desc: "Parthenocarpic"}]
      },
    {
      id: "watermelon",
      name: "Watermelon",
      category: "vegetables",
      type: "Hybrid",
      code: "TMR-WM",
      active: true,
      order: 10,
      description: "Red and yellow watermelon hybrids with high brix and excellent eating quality. Crimson sweet and premium types.",
      image: "images/products/watermelon.jpg",
      features: ["Red & yellow types", "High brix (12-14%)", "Good shipping quality", "Premium eating quality"],
      region: "All India",
      season: "Summer / Kharif",
      duration: "70-85 days",
      detailPage: false,
      hybrids: [{name: "Red Hybrid", desc: "Crimson sweet type"}, {name: "Yellow Hybrid", desc: "Premium, high brix"}]
      },
  // ----------------------------------------------------------------------
  // VEGETABLES — Individual SKUs (order 11+)
  // ----------------------------------------------------------------------
    {
      id: "tmwh2786",
      name: "Aasma (TMWH 2786)",
      category: "vegetables",
      type: "Hybrid",
      code: "TMWH2786",
      active: true,
      order: 11,
      description: "AASMA (TMWH 2786)\n• Ice box type Watermelon hybrid\n• Harvesting starts after 70-75 days of planti...",
      image: "images/products/TMWH2786.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "abeesh-tmth-222",
      name: "Abeesh (TMTH 222)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 12,
      description: "ABEESH (TMTH^22)\n• Tomato hybrid for fresh market and processing with very high yield potential\n•...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "aparna-tmph-408",
      name: "Aparna (TMPH 408)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 13,
      description: "Aparna (TMPH 408) — hybrid from Trimurti Seeds.",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmbi1314",
      name: "AYESHA (TMBI 1314)",
      category: "vegetables",
      type: "Hybrid",
      code: "TMBI1314",
      active: true,
      order: 14,
      description: "AYESHA (TMBI 1314) — hybrid from Trimurti Seeds.",
      image: "images/products/TMBI1314.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmwh2741",
      name: "Balma (TMWH 2741)",
      category: "vegetables",
      type: "Hybrid",
      code: "TMWH2741",
      active: true,
      order: 15,
      description: "BALMA(TMWH 2741)\n• Ice box type hybrid\n• Harvesting starts after 70 days after planting\n• Oblong ...",
      image: "images/products/TMWH2741.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "chamki",
      name: "Chamki",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 16,
      description: "CHAMKI (TMTH 209)\n• Tomato hybrid for fresh market with high yield potential\n• Picking starts fro...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "diya-tmth-208",
      name: "Diya (TMTH 208)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 17,
      description: "DIYA (TMTH 208)\n• Indeterminate type tomato hybrid with very high yield potential\n• Picking start...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "hema-plus-tmcu-1101",
      name: "Hema Plus (TMCU 1101)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 18,
      description: "HEMA+ (TMcC^Hl)\n• Cucumber hybrid for fresh market\n• Days to first appearance of male flower: 30-...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "holi",
      name: "Holi",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 19,
      description: "HOLI (TMTH206)\n• Tomato hybrid for fresh market purpose with high yield potential\n• Picking start...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "ila-1409",
      name: "Ila 1409",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 20,
      description: "ILA (TMBG 1409)\n• Bottle gourd hybrid for fresh market with very high yield potential\n• Long cyli...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "inam-tmcu-1111",
      name: "Inam (TMCU 1111)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 21,
      description: "INAM (TMCU 1111)\n• Cucumber hybrid for fresh market\n• Days to first fruit picking: 45-50 days\n• D...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmwh701",
      name: "Isha (TMWH 701)",
      category: "vegetables",
      type: "Hybrid",
      code: "TMWH701",
      active: true,
      order: 22,
      description: "ISHA (TMWH 701)\n• Dragon type hybrid with more fruits per plant\n• Harvesting starts from 80-85 da...",
      image: "images/products/TMWH701.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "ishq",
      name: "Ishq",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 23,
      description: "ISHQ (TMWH 702)\n• Sugar baby type hybrid with high yield potential\n• Harvesting starts from 75-80...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmbi1301",
      name: "Ista (TMBI 1301)",
      category: "vegetables",
      type: "Hybrid",
      code: "TMBI1301",
      active: true,
      order: 24,
      description: "ISTA (TMBI1301)\n• Bitter gourd hybrid having long spindle shaped fruits\n• Picking starts after 50...",
      image: "images/products/TMBI1301.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "jhalak-tmph-424",
      name: "Jhalak (TMPH 424)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 25,
      description: "JHALAK (TMPH 424)\n• Green Chilli hybrid with very high yield potential\n• Picking starts for green...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmwh711",
      name: "Kaabil (TMWH 711)",
      category: "vegetables",
      type: "Hybrid",
      code: "TMWH711",
      active: true,
      order: 26,
      description: "KAABIL(TMWH 711)\n• Ice box type watermelon hybrid\n• Harvesting starts from 75 - 80 days after pla...",
      image: "images/products/TMWH711.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmwh704",
      name: "Kaalia gold (TMWH 704)",
      category: "vegetables",
      type: "Hybrid",
      code: "TMWH704",
      active: true,
      order: 27,
      description: "Kaalia gold (TMWH 704) — hybrid from Trimurti Seeds.",
      image: "images/products/TMWH704.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "kashinath-tmpu-1818",
      name: "Kashinath (TMPU 1818)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 28,
      description: "KASHINATH (TMPU 1818)\n• Pumpkin hybrid with high yield and early maturity\n• Days to maturity: 90-...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "klik-tmph-401",
      name: "Klik (TMPH 401)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 29,
      description: "KLIK (TMPH 401)\n• Green Chilli hybrid\n• Picking starts for green chilli after 65-70 days from tra...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "leone-tmph-434",
      name: "LEONE (TMPH 434)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 30,
      description: "LEONE (TMPH 434) — hybrid from Trimurti Seeds.",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "mithikorn",
      name: "MithiKorn",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 31,
      description: "MITHIKORN (TMMH 8712)\n• Sweet com hybrid for fresh market with high yield potential\n• Picking sta...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "nagma-tmph-404",
      name: "Nagma (TMPH 404)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 32,
      description: "NAGMA (TMPH 404)\n• Dual purpose chilli hybrid (i.e. as green & dry chilli)\n• Picking starts for g...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "nivi-tmoh-306",
      name: "Nivi (TMOH 306)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 33,
      description: "NIVI (TMOH 306)\n• Okra hybrid with high yield potential\n• Early in picking and picking starts fro...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "nivi-gold-tmoh-303",
      name: "Nivi Gold (TMOH 303)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 34,
      description: "NIVI GOLD (TMOH 303)\n• Okra hybrid with very high yield potential\n• Picking starts from 45-50 day...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "poko-tmch-20008",
      name: "POKO (TMCH 20008)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 35,
      description: "POKO (TMCH 20008) — hybrid from Trimurti Seeds.",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "purvi-tmph-406",
      name: "Purvi (TMPH 406)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 36,
      description: "PURVI (TMPH 406)\n• Dry Chilli hybrid\n• Picking starts for dry chilli after l lO-l 15 days from tr...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "raima---tmph-417",
      name: "Raima + (TMPH 417)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 37,
      description: "RAIMA +\n• Green Chilli hybrid with high yield potential\n• Picking starts for green chilli after 6...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "real-star-tmch-20012",
      name: "REAL STAR (TMCH 20012)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 38,
      description: "REAL STAR (TMCH 20012) — hybrid from Trimurti Seeds.",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmbi1304",
      name: "Rishta (TMBI 1304)",
      category: "vegetables",
      type: "Hybrid",
      code: "TMBI1304",
      active: true,
      order: 39,
      description: "RISHTA (TMBI 1304)\n• Bitter gourd hybrid having long spindle shaped fruits\n• Dark Green fruits ar...",
      image: "images/products/TMBI1304.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "rumi-tmsg-1602",
      name: "Rumi (TMSG 1602)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 40,
      description: "RUMI (TMSG 1602)\n• Sponge gourd hybrid for fresh market with high yield potential\n• Picking start...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "rype-tmth-205",
      name: "Rype (TMTH 205)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 41,
      description: "RYPE (TMTH 205)\n• Hybrid for fresh market with high yield potential\n• Recommended for cultivation...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "sarla-tmbg-1404",
      name: "Sarla (TMBG 1404)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 42,
      description: "Sarla (TMBG 1404) — hybrid from Trimurti Seeds.",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "shivi-tmoh-307",
      name: "Shivi (TMOH 307)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 43,
      description: "SHIVI (TMOH 307)\n• Okra hybrid with high yield potential\n• Early picking and picking starts from ...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "shivi-gold",
      name: "Shivi gold",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 44,
      description: "SHIVI GOLD (TMOH 316)\n• Okra hybrid with high yield potential\n• Picking starts from 45-50 days\n• ...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tabla-tmpu-1836",
      name: "Tabla (TMPU 1836)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 45,
      description: "TABLA (TMPU1836)\n• Pumpkin hybrid with high yield and early maturity\n• Days to maturity: 80-90 da...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmbi1305",
      name: "Tanu (TMBI 1305)",
      category: "vegetables",
      type: "Hybrid",
      code: "TMBI1305",
      active: true,
      order: 46,
      description: "TANU (TMBI 1305)\n• Bitter gourd hybrid having Short Spindle-shaped fruits.\n• Picking starts after...",
      image: "images/products/TMBI1305.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tanya-tmsg-1601",
      name: "Tanya (TMSG 1601)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 47,
      description: "TANYA (TMSG 1601)\n• Sponge gourd hybrid for fresh market with high yield potential\n• Picking star...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmbg-3402",
      name: "TMBG 3402",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 48,
      description: "• Bottle gourd hybrid for fresh market\n• Medium long cylindrical fruits\n• Picking starts after 50...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmca-21006",
      name: "TMCA 21006",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 49,
      description: "TMCA 21006 — hybrid from Trimurti Seeds.",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmch-20824",
      name: "TMCH 20824",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 50,
      description: "TMCH 20824 — hybrid from Trimurti Seeds.",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmcu-3102",
      name: "TMCU 3102",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 51,
      description: "TMCU3102\n• Cucumber hybrid for fresh market\n• Days to first appearance of female flower after 30-...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmcu-3111",
      name: "TMCU 3111",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 52,
      description: "Cucumber hybrid for fresh market\nDays to first fruit picking: 45-50 days\nDays to first appearance...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmoh-2304",
      name: "TMOH 2304",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 53,
      description: "• Okra hybrid with high yield potential\n• Early picking and picking starts from 40-42 days\n• Easy...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmoh-2318",
      name: "TMOH 2318",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 54,
      description: "• Okra hybrid with high yield potential\n• Resistant to Yellow Vein Mosaic Virus (YVMV)\n• Picking ...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmoh-2322",
      name: "TMOH 2322",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 55,
      description: "• Okra hybrid with high yield potential\n• Resistant to Yellow Vein Mosaic Virus (YVMV)\n• Picking ...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmoh-2345",
      name: "TMOH 2345",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 56,
      description: "• Okra Hybrid with very high yield potential\n• Picking starts from 45-50 days after sowing\n• Erec...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmoh-2352",
      name: "TMOH 2352",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 57,
      description: "• Okra hybrid with very high yield potential\n• Picking starts from 42-46 days after sowing\n• Erec...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmoh-314",
      name: "TMOH 314",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 58,
      description: "• Okra hybrid with high yield potential\n• Highly tolerant to Yellow Vein Mosaic Virus (YVMV)\n• Pi...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmoh-329",
      name: "TMOH 329",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 59,
      description: "• Okra hybrid with very high yield potential\n• Picking starts from 45-50 days\n• Erect with tall p...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmoh-333",
      name: "TMOH 333",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 60,
      description: "TMOH 333 — hybrid from Trimurti Seeds.",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmov-36",
      name: "TMOV 36",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 61,
      description: "• Okra variety with high yield potential\n• Tolerant to Yellow Vein Mosaic Virus (YVMV)\n• Picking ...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmov-99",
      name: "TMOV 99",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 62,
      description: "Okra variety with high yield potential\n• Tolerant to Yellow Vein Mosaic Virus (YVMV)\n• Picking st...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmph-2441",
      name: "TMPH 2441",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 63,
      description: "• Green chili hybrid with very high yield potential\n• Picking starts for green chilli after 60-65...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmph-2446",
      name: "TMPH 2446",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 64,
      description: "• Green Chilli hybrid with very high yield potential\n• Picking starts for green chilli after 65-7...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmph-403-sivaranjani",
      name: "TMPH 403 (SIVARANJANI)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 65,
      description: "TMPH 403 (SIVARANJANI)\n• Dry Chilli hybrid with very high color value\n• Picking starts for dry ch...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmph-411",
      name: "TMPH 411",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 66,
      description: "• Dry Chilli hybrid with very high color value\n• Picking starts for dry chilli after 100-105 days...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmph-439",
      name: "TMPH 439",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 67,
      description: "• Hybrid ideal as green chilli\n• Picking starts for green chilli after 70-75 days from transplant...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmph-443",
      name: "TMPH 443",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 68,
      description: "• Green Chilli Hybrid with very high yield potential\n• Picking starts for green chilli after 60-6...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmph-444",
      name: "TMPH 444",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 69,
      description: "• Dual purpose chilli hybrid (i.e. as green & dry chilli)\n• Picking starts for green chilli after...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmph-449",
      name: "TMPH 449",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 70,
      description: "• Green Chilli Hybrid with high yield potential\n• Picking starts for green chilli after 65-70 day...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmph-463",
      name: "TMPH 463",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 71,
      description: "• Dual purpose chilli hybrid (i.e. as green & dry chilli)\n• Picking starts for green chilli after...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmph-489",
      name: "TMPH 489",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 72,
      description: "• Dual purpose chilli hybrid (i.e. as green & dry chilli)\n• Picking starts for green chilli after...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmpu-1827",
      name: "TMPU 1827",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 73,
      description: "TMPU 1827 — hybrid from Trimurti Seeds.",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmsg-3615",
      name: "TMSG 3615",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 74,
      description: "TMSG 3615 — hybrid from Trimurti Seeds.",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmth-215",
      name: "TMTH 215",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 75,
      description: "• Hybrid for fresh market with high yield potential\n• Recommended for Kharif, Rabi and Summer sea...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmth-2226",
      name: "TMTH 2226",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 76,
      description: "* Hybrid for fresh market with high yield potential\n• Recommended for both Kharif and Rabi season...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmth-2230",
      name: "TMTH 2230",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 77,
      description: "• Tomato hybrid for fresh market and processing purpose with very\nhigh yield potential\n• Semi-det...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmth-2267",
      name: "TMTH 2267",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 78,
      description: "• Tomato hybrid for fresh market with very high yield potential\n• Semi-determinate plant type\n• P...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmth-231",
      name: "TMTH 231",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 79,
      description: "• Tomato hybrid for fresh market purpose with very high yield potential\n• Picking starts from 60-...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmth-255",
      name: "TMTH 255",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 80,
      description: "• Tomato hybrid for fresh market with high yield potential\n• Recommended for year-round cultivati...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmth-288",
      name: "TMTH 288",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 81,
      description: "TMTH 228\n• Tomato hybrid for fresh market with high yield potential\n• Very widely adapted for cul...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmwh2710",
      name: "TMWH 2710",
      category: "vegetables",
      type: "Hybrid",
      code: "TMWH2710",
      active: true,
      order: 82,
      description: "• Dragon type Watermelon hybrid\n• Harvesting starts after 80-85 days of planting\n• Oblong fruits ...",
      image: "images/products/TMWH2710.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmwh2712",
      name: "TMWH 2712",
      category: "vegetables",
      type: "Hybrid",
      code: "TMWH2712",
      active: true,
      order: 83,
      description: "• Sugar baby type Watermelon hybrid\n• Harvesting starts after 80 - 85 days of planting\n• Round sh...",
      image: "images/products/TMWH2712.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmwh708",
      name: "Tohfa (TMWH 708)",
      category: "vegetables",
      type: "Hybrid",
      code: "TMWH708",
      active: true,
      order: 84,
      description: "TOHFA (TMWH 708)\n• Ice box type watermelon hybrid\n• Harvesting starts from 70-75 days after plant...",
      image: "images/products/TMWH708.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "veena-tmbg-1401",
      name: "Veena (TMBG 1401)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 85,
      description: "VEENA (TMBG 1401)\n• Bottle gourd hybrid for fresh market with high yield potential\n• Picking star...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "vishwanath",
      name: "Vishwanath",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 86,
      description: "VISHWANATH (TMRV 1610)\n• Mid-early maturing (Kharif: 115-120 days) Rice variety with high\nyield p...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "white-lily-tmca-21009",
      name: "WHITE LILY (TMCA 21009)",
      category: "vegetables",
      type: "Hybrid",
      code: "",
      active: true,
      order: 87,
      description: "WHITE LILY (TMCA 21009) — hybrid from Trimurti Seeds.",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
  // ======================================================================
  // FODDER — Category Summary Cards (order 1-3)
  // ======================================================================
    {
      id: "maize-fodder",
      name: "Maize Fodder",
      category: "fodder",
      type: "Hybrid",
      code: "TMR-FM",
      active: true,
      order: 1,
      description: "High-biomass multi-cut maize fodder hybrids for dairy and livestock. Nutritious and palatable green and dry fodder.",
      image: "images/products/maize-fodder.jpg",
      features: ["Multi-cut (3-4 cuts)", "High biomass", "Nutritious", "Palatable"],
      region: "All India",
      season: "Kharif / Rabi",
      duration: "55-65 days per cut",
      detailPage: false,
      hybrids: [{name: "Multi-Cut Fodder", desc: "High biomass, 3-4 cuts"}, {name: "Green Fodder", desc: "Nutritious, palatable"}]
      },
    {
      id: "sorghum-fodder",
      name: "Sorghum Fodder",
      category: "fodder",
      type: "Variety",
      code: "TMR-FS",
      active: true,
      order: 2,
      description: "Multi-cut and single-cut sorghum fodder varieties with sustained fodder supply and high dry matter content.",
      image: "images/products/sorghum-fodder.jpg",
      features: ["Multi-cut (4-5 cuts)", "High dry matter", "Good regrowth", "Drought tolerance"],
      region: "All India",
      season: "Kharif / Summer",
      duration: "50-60 days per cut",
      detailPage: false,
      hybrids: [{name: "Multi-Cut Variety", desc: "Sustained supply, 4-5 cuts"}, {name: "Single-Cut Variety", desc: "High dry matter"}]
      },
    {
      id: "cowpea-fodder",
      name: "Cowpea Fodder",
      category: "fodder",
      type: "Variety",
      code: "TMR-FC",
      active: true,
      order: 3,
      description: "Protein-rich cowpea fodder varieties for improved livestock nutrition. Dual-purpose options for fodder and green manure.",
      image: "images/products/cowpea-fodder.jpg",
      features: ["High protein (18-20% CP)", "Dual-purpose", "Good biomass", "Soil improvement"],
      region: "All India",
      season: "Kharif / Summer",
      duration: "45-55 days",
      detailPage: false,
      hybrids: [{name: "Fodder Variety", desc: "Protein-rich, 18-20% CP"}, {name: "Dual-Purpose", desc: "Fodder + green manure"}]
      },
  // ----------------------------------------------------------------------
  // FODDER — Individual SKUs (order 4+)
  // ----------------------------------------------------------------------
    {
      id: "charu-tmsh-1201",
      name: "Charu (TMSH 1201)",
      category: "fodder",
      type: "Hybrid",
      code: "",
      active: true,
      order: 4,
      description: "CHARU (TMSH 1201)\n• Multi-cut SSG hybrid with high yield potential\n• Good quality fodder with hig...",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmfh1208",
      name: "Charu Gold (TMFH 1208)",
      category: "fodder",
      type: "Hybrid",
      code: "TMFH1208",
      active: true,
      order: 5,
      description: "CHARU GOLD (TMFH 1208)\n• Sudan grass fodder hybrid with very high yielding potential\n• Growing up...",
      image: "images/products/TMFH1208.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmfh1222",
      name: "DAIRY DON (TMFH 1222)",
      category: "fodder",
      type: "Hybrid",
      code: "TMFH1222",
      active: true,
      order: 6,
      description: "DAIRY DON (TMFH 1222) — hybrid from Trimurti Seeds.",
      image: "images/products/TMFH1222.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmfh3211",
      name: "Samata (TMFH 3211)",
      category: "fodder",
      type: "Hybrid",
      code: "TMFH3211",
      active: true,
      order: 7,
      description: "SAMATA (TMFH 3211)\n• Multi-cut SSG hybrid with high yield potential\n• Good quality fodder with hi...",
      image: "images/products/TMFH3211.jpg",
      features: [],
      pdf: "brochures/TMFH3211.pdf",
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmfh3206",
      name: "Samata Speed (TMFH 3206)",
      category: "fodder",
      type: "Hybrid",
      code: "TMFH3206",
      active: true,
      order: 8,
      description: "SAMATA SPEED (TMFH 1206)\n• Good quality fodder with higher digestibility for livestock\n• Multi-cu...",
      image: "images/products/TMFH3206.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmfh1276",
      name: "Sweet Fora (TMFH 1276)",
      category: "fodder",
      type: "Hybrid",
      code: "TMFH1276",
      active: true,
      order: 9,
      description: "SWEET FORA (TMFH 1276)\n• Single cut Sweet Sorghum fodder but can be taken another cut\n• Juicy ste...",
      image: "images/products/TMFH1276.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tfx-1282",
      name: "TFX 1282",
      category: "fodder",
      type: "Hybrid",
      code: "",
      active: true,
      order: 10,
      description: "TFX 1282 — hybrid from Trimurti Seeds.",
      image: "",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmfh1241",
      name: "TMFH 1241",
      category: "fodder",
      type: "Hybrid",
      code: "TMFH1241",
      active: true,
      order: 11,
      description: "TMFH 1241 — hybrid from Trimurti Seeds.",
      image: "images/products/TMFH1241.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmfh1255",
      name: "TMFH 1255",
      category: "fodder",
      type: "Hybrid",
      code: "TMFH1255",
      active: true,
      order: 12,
      description: "TMFH 1255 — hybrid from Trimurti Seeds.",
      image: "images/products/TMFH1255.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmfh1275",
      name: "TOP DAIRY (TMFH 1275)",
      category: "fodder",
      type: "Hybrid",
      code: "TMFH1275",
      active: true,
      order: 13,
      description: "TOP DAIRY (TMFH 1275) — hybrid from Trimurti Seeds.",
      image: "images/products/TMFH1275.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
    {
      id: "tmfh1251",
      name: "Vitagraze (TMFH 1251)",
      category: "fodder",
      type: "Hybrid",
      code: "TMFH1251",
      active: true,
      order: 14,
      description: "VITAGRAZE (TaTh 1251)\n• Multi-cut forage bajra hybrid with high yield potential\n• Harvesting star...",
      image: "images/products/TMFH1251.jpg",
      features: [],
      detailPage: false,
      hybrids: []
      },
];

// Helper: get active products sorted by order
function getActiveProducts() {
  return PRODUCTS.filter(function(p) { return p.active !== false; })
    .sort(function(a, b) { return (a.order || 99) - (b.order || 99); });
}

// Helper: get products by category
function getProductsByCategory(category) {
  return getActiveProducts().filter(function(p) { return p.category === category; });
}
